[project]
name = 'open-voice'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.open-voice]
path = 'contracts/open-voice.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
